language: node_js
node_js:
  - 10.15.3
cache:
  directories:
  - node_modules
addons:
  code_climate
git:
  depth: 25
  quiet: true
before_script:
  - export CC_TEST_REPORTER_ID=8750ba1d833760b0775e34e5e18c7328d9f081a3ab331c8f345818d9d6a2236e
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test:coverage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
Collapse

